local rules = {
  {
    description = "HRiP SFX Archive",
    comment = {
      length = 32,
      offset = 144,
    },
    new_type = "b",
    signatures = {
      {
        offset = 5,
        pattern = {
          "S",
          "F",
          "X",
          "H",
        },
      },
    },
    type = "B",
  },
  {
    description = "Basic файл",
    new_type = "b",
    special_char = "!",
    type = "B",
  },
  {
    description = "Overlay",
    start = 19542,
    type = "O",
  },
  {
    description = "Overlay",
    start = 27766,
    type = "o",
  },
  {
    description = "Excess Deluxe Paint plug-in",
    start = 28263,
    type = "p",
  },
  {
    description = "Excess Deluxe Paint overlay",
    start = 31073,
    type = "l",
  },
  {
    description = "Excess Deluxe Paint texture",
    start = 30821,
    type = "t",
  },
  {
    description = "Excess Deluxe Paint effect",
    start = 30822,
    type = "e",
  },
  {
    description = "Real Commander module",
    start = 19779,
    type = "R",
  },
  {
    description = "Quick HyperText System file",
    start = 29800,
    type = "q",
  },
  {
    description = "Quick HyperText System compiled file",
    start = 29800,
    type = "q",
  },
  {
    description = "ZXZIP archive",
    start = 20553,
    type = "Z",
  },
  {
    description = "ZXRAR archive",
    start = 30842,
    type = "r",
  },
  {
    description = "ZXRAR volume",
    start = 30842,
  },
  {
    description = "HRiP archive",
    start = 28786,
    type = "h",
  },
  {
    description = "HRiP archive",
    signatures = {
      {
        offset = 0,
        pattern = {
          "H",
          "R",
          "i",
        },
      },
    },
  },
  {
    description = "HRiP volume",
    start = 28786,
  },
  {
    description = "Description file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 31337,
    type = "d",
  },
  {
    description = "Description file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 23113,
    type = "D",
  },
  {
    description = "Horror Word text",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 17490,
    type = "W",
  },
  {
    description = "Text file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 29816,
    type = "t",
  },
  {
    description = "Text file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 21592,
    type = "T",
  },
  {
    description = "Color screen",
    new_type = "s",
    no_secs = 27,
    size = 6912,
    special_char = "!",
  },
  {
    description = "B/W screen",
    new_type = "s",
    no_secs = 24,
    size = 6144,
    special_char = "!",
  },
  {
    description = "RGB packed screen",
    new_type = "s",
    start = 47104,
    type = "Y",
  },
  {
    description = "x2 packed screen",
    new_type = "s",
    start = 47104,
    type = "U",
  },
  {
    description = "Laser Compact 5.2 screen",
    new_type = "s",
    signatures = {
      {
        offset = 0,
        pattern = {
          "L",
          "C",
          "M",
          "P",
          "5",
        },
      },
    },
  },
  {
    description = "Laser Compact 5.2 screen with depacker",
    new_type = "s",
    signatures = {
      {
        offset = 0,
        pattern = {
          17,
          0,
          64,
          217,
          17,
          142,
          0,
          28,
          205,
          198,
          31,
          25,
          126,
          35,
          221,
          46,
        },
      },
    },
  },
  {
    description = "Laser Compact 5.0 screen",
    new_type = "s",
    start = 40005,
    type = "P",
  },
  {
    description = "Laser Compact 4 screen",
    new_type = "s",
    start = 40004,
    type = "P",
  },
  {
    description = "Laser Compact 4 screen with depacker",
    new_type = "s",
    signatures = {
      {
        offset = 0,
        pattern = {
          14,
          249,
          13,
          205,
          198,
          31,
          17,
          144,
        },
      },
    },
  },
  {
    description = "Multistudio RGB screen",
    new_type = "s",
    size = 12288,
    start = 0,
    type = "+",
  },
  {
    description = "RGB screen",
    new_type = "s",
    no_secs = 72,
    size = 18432,
    type = "C",
  },
  {
    description = "x2 screen",
    new_type = "s",
    no_secs = 54,
    size = 13824,
    type = "C",
  },
  {
    description = "Sprite Editor file",
    new_type = "s",
    start = 36861,
    type = "G",
  },
  {
    description = "Standart font 8x8",
    no_secs = 3,
    size = 768,
    type = "C",
  },
  {
    description = "256 chars font 4x8",
    no_secs = 8,
    size = 2048,
  },
  {
    description = "Screen Crasher packed screen",
    new_type = "s",
    start = 40000,
    type = "$",
  },
  {
    description = "HardCore 4x4 chunk set",
    start = 9032,
    type = "C",
  },
  {
    description = "HardCore 4x4 chunk set (output)",
    start = 9064,
    type = "C",
  },
  {
    description = "HardCore 4x4 chunk screen",
    start = 9288,
    type = "C",
  },
  {
    description = "HardCore 4x4 chunk screen (packed)",
    start = 9320,
    type = "C",
  },
  {
    description = "Asm source (XAS)",
    group = "asm",
    comment = {
      length = 29,
      offset = 0,
    },
    new_type = "a",
    special_char = "!",
    start = 21313,
    type = "x",
  },
  {
    description = "Asm source (XAS)",
    group = "asm",
    comment = {
      length = 29,
      offset = 0,
    },
    new_type = "a",
    special_char = "!",
    start = 21313,
    type = "X",
  },
  {
    description = "Asm source (XAS)",
    group = "asm",
    comment = {
      length = 29,
      offset = 0,
    },
    new_type = "a",
    special_char = "!",
    start = 21345,
    type = "X",
  },
  {
    description = "Asm source (ALASM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 0,
    type = "H",
  },
  {
    description = "Alasm configuration file",
    size = 3328,
    start = 60928,
    type = "O",
  },
  {
    description = "Asm source",
    new_type = "a",
    special_char = "!",
    start = 19795,
    type = "A",
  },
  {
    description = "Asm source (ZX ASM 3.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 35151,
    type = "C",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 28019,
    type = "a",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 8224,
    type = "C",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 28001,
    type = "a",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 29537,
    type = "z",
  },
  {
    description = "Asm source (MASM 1.1)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 38667,
    type = "a",
  },
  {
    description = "Asm source (MASM 1.1)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 38821,
    type = "a",
  },
  {
    description = "Asm source (TASM 2.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 38750,
    type = "C",
  },
  {
    description = "Asm source (TASM 3.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 39221,
    type = "A",
  },
  {
    description = "Asm source (TASM by XLD)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 40872,
    type = "A",
  },
  {
    description = "Asm source (STORM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 49163,
    type = "C",
  },
  {
    description = "Asm source (STORM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 49155,
    type = "C",
  },
  {
    description = "Asm source (STORM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 49163,
    type = "R",
  },
  {
    description = "ASM 2.00 module",
    comment = {
      length = 45,
      offset = 24,
    },
    new_type = "m",
    signatures = {
      {
        offset = 69,
        pattern = {
          22,
          13,
          1,
          nil,
          nil,
          237,
          81,
          6,
          191,
          237,
          113,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.12 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          205,
          82,
          0,
          nil,
          nil,
          nil,
          nil,
          113,
          198,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.12 module (2)",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          205,
          82,
          0,
          nil,
          nil,
          nil,
          nil,
          223,
          4,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.11 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          205,
          82,
          0,
          nil,
          nil,
          nil,
          nil,
          23,
          198,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.11 module (2)",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          205,
          82,
          0,
          nil,
          nil,
          nil,
          nil,
          141,
          4,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.10 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          175,
          33,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          249,
          197,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.03 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          175,
          33,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          204,
          196,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 0.12 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          175,
          33,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          167,
          196,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 0.xx module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          175,
          33,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          120,
          196,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Vortex Tracker 1.0 module",
    comment = {
      length = 69,
      offset = 30,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          "V",
          "o",
          "r",
          "t",
          "e",
          "x",
          " ",
          "T",
          "r",
          "a",
          "c",
          "k",
          "e",
          "r",
          " ",
          "I",
          "I",
          " ",
          "1",
          ".",
          "0",
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 1.1 module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          205,
          nil,
          nil,
          195,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 1.1 module",
    new_type = "m",
    special_char = "!",
    start = 50886,
    type = "P",
  },
  {
    description = "ProTracker 2.0 module",
    comment = {
      length = 30,
      offset = 2692,
    },
    new_type = "m",
    signatures = {
      {
        offset = 570,
        pattern = {
          243,
          229,
          34,
          nil,
          nil,
          229,
          126,
          50,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 2.1 compiled module with player",
    new_type = "m",
    comment = {
      length = 30,
      offset = 2708,
    },
    signatures = {
      {
        offset = 9,
        pattern = {
          " ",
          "P",
          "R",
          "O",
          "T",
          "R",
          "A",
          "C",
          "K",
          "E",
          "R",
          " ",
          "2",
          ".",
          "1",
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 2.4 compiled module by PhF",
    comment = {
      length = 44,
      offset = 2730,
    },
    new_type = "m",
    signatures = {
      {
        offset = 2583,
        pattern = {
          "N",
          "e",
          "w",
          " ",
          "S",
          "o",
          "u",
          "n",
          "d",
          "T",
          "r",
          "a",
          "c",
          "k",
          " ",
          "P",
          "l",
          "a",
          "y",
          "e",
          "r",
          " ",
          "B",
          "y",
          " ",
          "P",
          "H",
          "A",
          "N",
          "T",
          "O",
          "M",
          " ",
          "F",
          "A",
          "M",
          "I",
          "L",
          "Y"
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Protracker 2.4 by PhF module",
    comment = {
      length = 30,
      offset = 101,
    },
    new_type = "m",
    special_char = "!",
    start = 51781,
    type = "M",
  },
  {
    description = "Protracker 3.x compiled song",
    comment = {
      length = 69,
      offset = 3647,
    },
    new_type = "m",
    signatures = {
      {
        offset = 11,
        pattern = {
          32,
          "P",
          "T",
          32,
          "3",
          32,
        },
      },
    },
    special_char = "!",
  },
  {
-- ProTracker 3.x module
    description = "ProTracker {ver} module",
    description_vars = { ver = { offset = 11, type = "ascii", length=3 } },
    comment = {
      -- length = 69,
      length = 32,
      offset = 30,
    },
    author = {
      offset = 66,
      length = 32,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          "P",
          "r",
          "o",
          "T",
          "r",
          "a",
          "c",
          "k",
          "e",
          "r",
          " ",
          "3",
          ".",
          nil,
          " ",
          "c",
          "o",
          "m",
          "p",
          "i",
          "l",
          "a",
          "t",
          "i",
          "o",
          "n",
          " ",
          "o",
          "f",
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 3.x module",
    comment = {
      length = 70,
      offset = 3646,
    },
    new_type = "m",
    signatures = {
      {
        offset = 44,
        pattern = {
          243,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          1,
          100,
          0,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Protracker 3.3 module",
    comment = {
      length = 69,
      offset = 30,
    },
    new_type = "m",
    special_char = "!",
    start = 52769,
    type = "m",
  },
  {
    description = "ProTracker 3.5x module",
    comment = {
      length = 69,
      offset = 3512,
    },
    new_type = "m",
    signatures = {
      {
        offset = 46,
        pattern = {
          243,
          237,
          115,
          nil,
          nil,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          1,
          100,
          0,
          9,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Sound Tracker 3 tune id",
    new_type = "m",
    size = 60,
    special_char = "!",
    start = 52739,
    type = "L",
  },
  {
    description = "Sound Tracker module",
    new_type = "m",
    special_char = "!",
    start = 25000,
    type = "S",
  },
  {
    description = "Sound Tracker Pro 48k module",
    new_type = "m",
    special_char = "!",
    start = 25000,
    type = "f",
  },
  {
    description = "Sound Tracker Pro compiled module",
    comment = {
      length = 26,
      offset = 44,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          195,
          nil,
          nil,
          237,
          nil,
          nil,
          nil,
          195,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ST Pro module (version)",
    comment = {
      length = 27,
      offset = 37,
    },
    new_type = "m",
    signatures = {
      {
        offset = 72,
        pattern = {
          243,
          33,
          nil,
          nil,
          34,
          nil,
          nil,
          62,
          nil,
          50,
          nil,
          nil,
          50,
          nil,
          nil,
          50,
          nil,
          nil,
          126,
          35,
          50,
          nil,
          nil,
          205,
          nil,
          nil,
          126,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SoundTracker module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          195,
          nil,
          nil,
          nil,
          126,
          50,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SoundTracker (v3.0) module",
    comment = {
      length = 27,
      offset = 48,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          175,
          6,
          191,
          195,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ST module (KSA compilation)",
    comment = {
      length = 28,
      offset = 39,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          195,
          nil,
          nil,
          195,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ST module (FLASH compilation)",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          151,
          50,
          nil,
          nil,
          50,
          nil,
          nil,
          33,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Fast tracker 1.0 module",
    comment = {
      length = 43,
      offset = 7,
    },
    new_type = "m",
    signatures = {
      {
        offset = 51,
        pattern = {
          "F",
          "a",
          "s",
          "t",
          " ",
          "T",
          "r",
          "a",
          "c",
          "k",
          "e",
          "r",
          " ",
          "v",
          "1",
        },
      },
    },
    special_char = "!",
  },
  {
    description = "FastTracker v1.00 module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          243,
          33,
          nil,
          nil,
          53,
          32,
          26,
          205,
          nil,
          nil,
          62,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "FastTracker v2.00 module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          195,
          nil,
          nil,
          243,
          33,
          nil,
          nil,
          53,
          194,
          nil,
          nil,
          54,
          nil,
          62,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Global Digital Editor module",
    new_type = "m",
    special_char = "!",
    start = 48640,
    type = "m",
  },
  {
    description = "Global Tracker module wo/player",
    comment = {
      length = 32,
      offset = 7,
    },
    new_type = "m",
    signatures = {
      {
        offset = 1,
        pattern = {
          "G",
          "T",
          "R",
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Global Tracker module",
    new_type = "m",
    signatures = {
      {
        offset = 152,
        pattern = {
          0,
          225,
          0,
          214,
          0,
          200,
          0,
          189,
          0,
          178,
          0,
          168,
          0,
          159,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Pro Sound Creator v{ver} module wo/player",
    description_vars = { ver = { offset = 5, type = "ascii", length = 4 } },
    comment = {
      length = 21,
      offset = 25,
    },
    author = {
      length = 15,
      offset = 49,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          "P",
          "S",
          "C",
          " ",
          "V",
          "1",
          ".",
        },
      },
    },
    special_char = "!",
    start = 21328,
    type = "M",
  },
  {
    description = "Pro Sound Creator 1.xx module",
    comment = {
      length = 45,
      offset = 3002,
    },
    new_type = "m",
    signatures = {
      {
        offset = 32,
        pattern = {
          34,
          nil,
          nil,
          235,
          33,
          76,
          0,
          25,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          34,
          nil,
          nil,
          43,
          43,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Pro Sound Maker v4.1 module",
    new_type = "m",
    signatures = {
      {
        offset = 301,
        pattern = {
          221,
          53,
          15,
          240,
          221,
          110,
          0,
          221,
          102,
          1,
          205,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SQ Tracker module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          62,
          nil,
          50,
          nil,
          nil,
          50,
          nil,
          nil,
          50,
          nil,
          nil,
          1,
          1,
          1,
          205,
          nil,
          nil,
          42,
          nil,
          nil,
          221,
          33,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SuperSonic module wo/player",
    new_type = "m",
    signatures = {
      {
        offset = 7,
        pattern = {
          "(",
          "C",
          ")",
          " ",
          "K",
          "L",
          "A",
          "V",
          " ",
          34,
          "S",
          "_",
          "S",
          "O",
          "N",
          "I",
          "C",
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SuperSonic module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          195,
          nil,
          nil,
          195,
          nil,
          nil,
          230,
          3,
          135,
          95,
          22,
          0,
          33,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Digital Music Maker module",
    new_type = "m",
    special_char = "!",
    start = 25000,
    type = "T",
  },
  {
    description = "Digital Studio tune",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "S",
  },
  {
    description = "Digital Studio module",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "M",
  },
  {
    description = "Digital Designer module",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "d",
  },
  {
    description = "Digital Designer module",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "#",
  },
  {
    description = "Sample Tracker module",
    new_type = "m",
    special_char = "!",
    start = 35644,
    type = "s",
  },
  {
    description = "Sample Tracker module",
    new_type = "m",
    special_char = "!",
    start = 29280,
    type = "S",
  },
  {
    description = "Ultrasonic mod",
    new_type = "m",
    size = 25711,
    special_char = "!",
    start = 27987,
    type = "U",
  },
  {
    description = "Ultrasonic block",
    new_type = "m",
    size = 27503,
    special_char = "!",
    start = 27746,
    type = "1",
  },
  {
    description = "ZX-AMP Library",
    new_type = "m",
    special_char = "!",
    start = 21058,
    type = "L",
  },
  {
    description = "ZX-AMP Players pack",
    start = 20557,
    type = "A",
  },
  {
    description = "Packed with HRUST 2.1",
    signatures = {
      {
        offset = 0,
        pattern = {
          104,
          114,
          50,
          49,
        },
      },
    },
  },
  {
    description = "Packed with HRUST 1.x",
    signatures = {
      {
        offset = 14,
        pattern = {
          213,
          237,
          176,
          19,
          19,
          213,
          221,
          225,
          14,
          6,
          9,
          237,
          176,
        },
      },
    },
  },
  {
    description = "Packed with HRUST 1.x w/o depacker",
    signatures = {
      {
        offset = 0,
        pattern = {
          72,
          82,
        },
      },
    },
  },
  {
    description = "Packed with HRUM 3.5i",
    signatures = {
      {
        offset = 5,
        pattern = {
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          237,
          176,
          17,
          nil,
          nil,
          217,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          201,
        },
      },
    },
  },
  {
    description = "Packed with Rip",
    start = 28777,
    type = "R",
  },
  {
    description = "Packed with LZS",
    signatures = {
      {
        offset = 0,
        pattern = {
          205,
          nil,
          nil,
          243,
          237,
          115,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          201,
        },
      },
    },
  },
  {
    description = "Packed with CC3",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          nil,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          201,
        },
      },
    },
  },
  {
    description = "Packed with CC4",
    signatures = {
      {
        offset = 0,
        pattern = {
          205,
          nil,
          nil,
          59,
          59,
          225,
          1,
          nil,
          nil,
          9,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          201,
        },
      },
    },
  },
  {
    description = "Packed with CC4 (DI)",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          205,
          nil,
          nil,
          59,
          59,
          225,
          1,
          nil,
          nil,
          9,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          201,
        },
      },
    },
  },
  {
    description = "Packed with MS Pack",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          237,
          115,
          nil,
          nil,
          217,
          34,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          217,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          nil,
          nil,
          249,
          225,
        },
      },
    },
  },
  {
    description = "Packed with MS Pack w/o depacker",
    signatures = {
      {
        offset = 0,
        pattern = {
          "M",
          "s",
          "P",
          "k",
        },
      },
    },
  },
  {
    description = "Packed with PCD 6.xx",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          201,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
        },
      },
    },
  },
  {
    description = "Packed with PCD 6.xx (2)",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          237,
          nil,
          1,
          nil,
          nil,
          217,
          34,
          nil,
          nil,
          33,
        },
      },
    },
  },
  {
    description = "Packed with DSQ",
    signatures = {
      {
        offset = 0,
        pattern = {
          17,
          nil,
          nil,
          33,
          nil,
          nil,
          213,
          1,
          nil,
          nil,
          nil,
          nil,
          17,
          nil,
          nil,
          33,
          nil,
          nil,
          1,
          nil,
          nil,
          201,
          nil,
          nil,
          1,
          nil,
          nil,
          33,
          nil,
          nil,
          217,
          229,
        },
      },
    },
  },
  {
    description = "Packed with Trush Packer",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          nil,
          nil,
          217,
          229,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          235,
          35,
          221,
          33,
          nil,
          nil,
          221,
          57,
          249,
        },
      },
    },
  },
  {
    description = "Packed with ESV",
    signatures = {
      {
        offset = 0,
        pattern = {
          243,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          213,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          201,
          nil,
          nil,
          33,
          nil,
          nil,
          1,
        },
      },
    },
  },
  {
    description = "Packed with Game Packer",
    signatures = {
      {
        offset = 0,
        pattern = {
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          213,
          1,
          nil,
          nil,
          nil,
          nil,
          33,
          nil,
          nil,
          17,
          nil,
          nil,
          1,
          nil,
          nil,
          nil,
          nil,
          19,
          235,
          17,
          nil,
          nil,
          201,
          124,
          181,
        },
      },
    },
  },
  {
    description = "ZX Word text",
    new_type = "t",
    show_header = false,
    special_char = "!",
    type = "W",
  },
  {
    description = "BGE plugin",
    type = ">",
  },
  {
    description = "Asm source (TASM 4.12)",
    new_type = "a",
    special_char = "!",
    type = "A",
  },
}

return {
  rules = rules,
  formats = rules,
}
