local rules = {
  {
    description = "HRiP SFX Archive",
    comment = {
      length = 32,
      offset = 144,
    },
    new_type = "b",
    signatures = {
      {
        offset = 5,
        pattern = "SFXH",
      },
    },
    type = "B",
  },
  {
    description = "Basic файл",
    new_type = "b",
    special_char = "!",
    type = "B",
    group = "basic",
  },
  {
    description = "Overlay",
    start = 19542,
    type = "O",
  },
  {
    description = "Overlay",
    start = 27766,
    type = "o",
  },
  {
    description = "Excess Deluxe Paint plug-in",
    start = 28263,
    type = "p",
  },
  {
    description = "Excess Deluxe Paint overlay",
    start = 31073,
    type = "l",
  },
  {
    description = "Excess Deluxe Paint texture",
    start = 30821,
    type = "t",
  },
  {
    description = "Excess Deluxe Paint effect",
    start = 30822,
    type = "e",
  },
  {
    description = "Real Commander module",
    start = 19779,
    type = "R",
  },
  {
    description = "Quick HyperText System file",
    start = 29800,
    type = "q",
  },
  {
    description = "Quick HyperText System compiled file",
    start = 29800,
    type = "q",
  },
  {
    description = "ZXZIP archive",
    start = 20553,
    type = "Z",
  },
  {
    description = "ZXRAR archive",
    start = 30842,
    type = "r",
  },
  {
    description = "ZXRAR volume",
    start = 30842,
  },
  {
    description = "HRiP archive",
    start = 28786,
    type = "h",
  },
  {
    description = "HRiP archive",
    signatures = {
      {
        offset = 0,
        pattern = "HRi",
      },
    },
  },
  {
    description = "HRiP volume",
    start = 28786,
  },
  {
    description = "Description file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 31337,
    type = "d",
  },
  {
    description = "Description file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 23113,
    type = "D",
  },
  {
    description = "Horror Word text",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 17490,
    type = "W",
  },
  {
    description = "Text file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 29816,
    type = "t",
  },
  {
    description = "Text file",
    new_type = "t",
    show_header = false,
    special_char = "!",
    start = 21592,
    type = "T",
  },
  {
    description = "Color screen",
    new_type = "s",
    no_secs = 27,
    size = 6912,
    special_char = "!",
  },
  {
    description = "B/W screen",
    new_type = "s",
    no_secs = 24,
    size = 6144,
    special_char = "!",
  },
  {
    description = "RGB packed screen",
    new_type = "s",
    start = 47104,
    type = "Y",
  },
  {
    description = "x2 packed screen",
    new_type = "s",
    start = 47104,
    type = "U",
  },
  {
    description = "Laser Compact 5.2 screen",
    new_type = "s",
    signatures = {
      {
        offset = 0,
        pattern = "LCMP5",
      },
    },
  },
  {
    description = "Laser Compact 5.2 screen with depacker",
    new_type = "s",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x11,
          0x00,
          0x40,
          0xD9,
          0x11,
          0x8E,
          0x00,
          0x1C,
          0xCD,
          0xC6,
          0x1F,
          0x19,
          0x7E,
          0x23,
          0xDD,
          0x2E,
        },
      },
    },
  },
  {
    description = "Laser Compact 5.0 screen",
    new_type = "s",
    start = 40005,
    type = "P",
  },
  {
    description = "Laser Compact 4 screen",
    new_type = "s",
    start = 40004,
    type = "P",
  },
  {
    description = "Laser Compact 4 screen with depacker",
    new_type = "s",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x0E,
          0xF9,
          0x0D,
          0xCD,
          0xC6,
          0x1F,
          0x11,
          0x90,
        },
      },
    },
  },
  {
    description = "Multistudio RGB screen",
    new_type = "s",
    size = 12288,
    start = 0,
    type = "+",
  },
  {
    description = "RGB screen",
    new_type = "s",
    no_secs = 72,
    size = 18432,
    type = "C",
  },
  {
    description = "x2 screen",
    new_type = "s",
    no_secs = 54,
    size = 13824,
    type = "C",
  },
  {
    description = "Sprite Editor file",
    new_type = "s",
    start = 36861,
    type = "G",
  },
  {
    description = "Standart font 8x8",
    no_secs = 3,
    size = 768,
    type = "C",
  },
  {
    description = "256 chars font 4x8",
    no_secs = 8,
    size = 2048,
  },
  {
    description = "Screen Crasher packed screen",
    new_type = "s",
    start = 40000,
    type = "$",
  },
  {
    description = "HardCore 4x4 chunk set",
    start = 9032,
    type = "C",
  },
  {
    description = "HardCore 4x4 chunk set (output)",
    start = 9064,
    type = "C",
  },
  {
    description = "HardCore 4x4 chunk screen",
    start = 9288,
    type = "C",
  },
  {
    description = "HardCore 4x4 chunk screen (packed)",
    start = 9320,
    type = "C",
  },
  {
    description = "Asm source (XAS)",
    group = "asm",
    comment = {
      length = 29,
      offset = 0,
    },
    new_type = "a",
    special_char = "!",
    start = 21313,
    type = "x",
  },
  {
    description = "Asm source (XAS)",
    group = "asm",
    comment = {
      length = 29,
      offset = 0,
    },
    new_type = "a",
    special_char = "!",
    start = 21313,
    type = "X",
  },
  {
    description = "Asm source (XAS)",
    group = "asm",
    comment = {
      length = 29,
      offset = 0,
    },
    new_type = "a",
    special_char = "!",
    start = 21345,
    type = "X",
  },
  {
    description = "Asm source (ALASM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 0,
    type = "H",
  },
  {
    description = "Alasm configuration file",
    size = 3328,
    start = 60928,
    type = "O",
  },
  {
    description = "Asm source",
    new_type = "a",
    special_char = "!",
    start = 19795,
    type = "A",
  },
  {
    description = "Asm source (ZX ASM 3.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 35151,
    type = "C",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 28019,
    type = "a",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 8224,
    type = "C",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 28001,
    type = "a",
  },
  {
    description = "Asm source (ZX ASM 3.10)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 29537,
    type = "z",
  },
  {
    description = "Asm source (MASM 1.1)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 38821,
    type = "a",
  },
  {
    description = "Asm source (MASM 2.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 38667,
    type = "a",
  },
  {
    description = "Asm source (MASM 3.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 37155,
    type = "a",
  },
  {
    description = "Asm source (TASM 2.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 38750,
    type = "C",
  },
  {
    description = "Asm source (TASM 3.0)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 39221,
    type = "A",
  },
  {
    description = "Asm source (TASM by XLD)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 40872,
    type = "A",
  },
  {
    description = "Asm source (TASM 4.12)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start_lt = 4097,
    type = "A",
  },
  {
    description = "Asm source (STORM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 49163,
    type = "C",
  },
  {
    description = "Asm source (STORM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 49155,
    type = "C",
  },
  {
    description = "Asm source (STORM)",
    group = "asm",
    new_type = "a",
    special_char = "!",
    start = 49163,
    type = "R",
  },
  {
    description = "ASM 2.00 module",
    comment = {
      length = 45,
      offset = 24,
    },
    new_type = "m",
    signatures = {
      {
        offset = 69,
        pattern = {
          0x16,
          0x0D,
          0x01,
          nil,
          nil,
          0xED,
          0x51,
          0x06,
          0xBF,
          0xED,
          0x71,
        },
      },
    },
    special_char = "!",
  },
  -- ASC Sound Master 1.13+ (no player). ID is scanned in the first N TR-DOS sectors;
  -- title/author are relative to the matched signature start (± offset_from_sig).
  {
    description = "ASM 1.13+ module",
    group = "trackers",
    new_type = "m",
    special_char = "!",
    scan_sectors = 1, -- search only the first 256 bytes for the ID
    signatures = {
      { pattern = "ASM 1.13+ COMPILER:", scan = true },
    },
    -- prefix(19) + title(20) + " BY "(4) + author(20)
    comment = {
      length = 20,
      offset_from_sig = 19, -- right after the 19-byte ID prefix
    },
    author = {
      length = 20,
      offset_from_sig = 43, -- 19 + 20 + 4
    },
  },
  {
    description = "ASM 1.12 module",
    group = "trackers",
    comment = {
      length = 20,
      offset = 39,
    },
    author = {
      length = 20,
      offset = 63,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xCD,
          0x52,
          0x00,
          0x3B,
          0x3B,
          nil,
          nil,
          0xDF,
          0x04,
        },
      },
      {
        offset = 83,
        pattern = {
          0xCD,
          0x52,
          0x00,
          nil,
          nil,
          nil,
          nil,
          0x71,
          0xC6,
        },
      },

    },
    special_char = "!",
  },
  {
    description = "ASM 1.11 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xCD,
          0x52,
          0x00,
          nil,
          nil,
          nil,
          nil,
          0x17,
          0xC6,
        },
      },
      {
        offset = 83,
        pattern = {
          0xCD,
          0x52,
          0x00,
          nil,
          nil,
          nil,
          nil,
          0x8D,
          0x04,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.10 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xAF,
          0x21,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          0xF9,
          0xC5,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 1.03 module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xAF,
          0x21,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          0xCC,
          0xC4,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 0.12 module",
    group = "trackers",
    comment = {
      length = 20,
      offset = 39,
    },
    author = {
      length = 20,
      offset = 63,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xAF,  -- XOR A
          0x21,  -- LD HL, ADDR
          nil,
          nil,
          0x11,  -- LD DE, ADDR
          nil,
          nil,
          0x01,  -- LD BC, LEN
          nil,
          nil,
          0x77,  -- LD (HL), A
          0xED,  -- LDIR
          0xB0,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          0xA7,
          0xC4,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ASM 0.xx module",
    comment = {
      length = 45,
      offset = 38,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xAF,
          0x21,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          0x78,
          0xC4,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Vortex Tracker 1.0 module",
    comment = {
      length = 69,
      offset = 30,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = "Vortex Tracker II 1.0",
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 1.1 module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xCD,
          nil,
          nil,
          0xC3,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 1.1 module",
    new_type = "m",
    special_char = "!",
    start = 50886,
    type = "P",
  },
  {
    description = "ProTracker 2.0 module",
    comment = {
      length = 30,
      offset = 2692,
    },
    new_type = "m",
    signatures = {
      {
        offset = 570,
        pattern = {
          0xF3,
          0xE5,
          0x22,
          nil,
          nil,
          0xE5,
          0x7E,
          0x32,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 2.1 compiled module with player",
    new_type = "m",
    comment = {
      length = 30,
      offset = 2708,
    },
    signatures = {
      {
        offset = 9,
        pattern = " PROTRACKER 2.1",
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 2.4 compiled module by PhF",
    comment = {
      length = 44,
      offset = 2730,
    },
    new_type = "m",
    signatures = {
      {
        offset = 2583,
        pattern = "New SoundTrack Player By PHANTOM FAMILY",
      },
    },
    special_char = "!",
  },
  {
    description = "Protracker 2.4 by PhF module",
    comment = {
      length = 30,
      offset = 101,
    },
    new_type = "m",
    special_char = "!",
    start = 51781,
    type = "M",
  },
  {
    description = "Protracker 3.x compiled song",
    comment = {
      length = 69,
      offset = 3647,
    },
    new_type = "m",
    signatures = {
      {
        offset = 11,
        pattern = " PT 3 ",
      },
    },
    special_char = "!",
  },
  {
-- ProTracker 3.x module
    description = "ProTracker {ver} module",
    description_vars = { ver = { offset = 11, type = "ascii", length=3 } },
    group = "trackers",
    comment = {
      -- length = 69,
      length = 32,
      offset = 30,
    },
    author = {
      offset = 66,
      length = 32,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = "ProTracker 3.? compilation of"
      },
    },
    special_char = "!",
  },
  {
    description = "ProTracker 3.x module",
    comment = {
      length = 70,
      offset = 3646,
    },
    new_type = "m",
    signatures = {
      {
        offset = 44,
        pattern = {
          0xF3,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x01,
          0x64,
          0x00,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Protracker 3.3 module",
    comment = {
      length = 69,
      offset = 30,
    },
    new_type = "m",
    special_char = "!",
    start = 52769,
    type = "m",
  },
  {
    description = "ProTracker 3.5x module",
    comment = {
      length = 69,
      offset = 3512,
    },
    new_type = "m",
    signatures = {
      {
        offset = 46,
        pattern = {
          0xF3,
          0xED,
          0x73,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x01,
          0x64,
          0x00,
          0x09,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Sound Tracker 3 tune id",
    new_type = "m",
    size = 60,
    special_char = "!",
    start = 52739,
    type = "L",
  },
  {
    description = "Sound Tracker module (STC)",
    group = "trackers",
    new_type = "m",
    special_char = "!",
    start = 25000,
    type = "S",
    signatures = {
      {
        offset = 7,
        pattern = "SONG BY ST COMPILE",
      },
      {
        offset = 7,
        pattern = "SONG BY MB COMPILE",
      },
      {
        offset = 7,
        pattern = "SOUND TRACKER v1.3",
      },
      {
        offset = 7,
        pattern = " COMPILED BY IMP !",
      },

    }
  },
  {
    description = "Sound Tracker module (ST1)",
    group = "trackers",
    new_type = "m",
    special_char = "!",
    start = 25000,
    size = 7617,
    type = "S",
  },
  {
    description = "Sound Tracker Pro compiled module",
    group = "trackers",
    comment = {
      length = 26,
      offset = 44,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21, -- LD HL, NN
          nil,
          nil,
          0xC3, -- JP
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xED, -- LD BC, (mem)
          0x4B,
          nil,
          nil,
          0xC3, -- JP
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Sound Tracker Pro module",
    new_type = "m",
    special_char = "!",
    start = 0,
    type = "F",
  },
  {
    description = "Sound Tracker Pro module",
    new_type = "m",
    special_char = "!",
    start = 25000, -- after depacker
    type = "F",
  },
  {
    description = "Sound Tracker Pro 48K module",
    new_type = "m",
    special_char = "!",
    start = 25000,
    type = "f",
  },
  {
    description = "ST Pro module (version)",
    comment = {
      length = 27,
      offset = 37,
    },
    new_type = "m",
    signatures = {
      {
        offset = 72,
        pattern = {
          0xF3,
          0x21,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x3E,
          nil,
          0x32,
          nil,
          nil,
          0x32,
          nil,
          nil,
          0x32,
          nil,
          nil,
          0x7E,
          0x23,
          0x32,
          nil,
          nil,
          0xCD,
          nil,
          nil,
          0x7E,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SoundTracker module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          nil,
          0x7E,
          0x32,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SoundTracker (v3.0) module",
    comment = {
      length = 27,
      offset = 48,
    },
    new_type = "m",
    signatures = {
      {
        offset = 83,
        pattern = {
          0xAF,
          0x06,
          0xBF,
          0xC3,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ST module (KSA compilation)",
    comment = {
      length = 28,
      offset = 39,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xC3,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "ST module (FLASH compilation)",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0x97,
          0x32,
          nil,
          nil,
          0x32,
          nil,
          nil,
          0x21,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Fast Tracker v{ver} module",
    description_vars = { ver = { offset = 65, type = "ascii", length = 4 } },
    group = "trackers",
    comment = {
      length = 43,
      offset = 7,
    },
    new_type = "m",
    signatures = {
      {
        offset = 51,
        pattern = "Fast Tracker v1"
      },
    },
    special_char = "!",
  },
  {
    description = "Fast Tracker v1.00 module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xF3,
          0x21,
          nil,
          nil,
          0x35,
          0x20,
          0x1A,
          0xCD,
          nil,
          nil,
          0x3E,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "FastTracker v2.00 module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xF3,
          0x21,
          nil,
          nil,
          0x35,
          0xC2,
          nil,
          nil,
          0x36,
          nil,
          0x3E,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Global Digital Editor module",
    new_type = "m",
    special_char = "!",
    start = 48640,
    type = "m",
  },
  {
    description = "Global Tracker module wo/player",
    group = "trackers",
    comment = {
      length = 32,
      offset = 7,
    },
    new_type = "m",
    signatures = {
      {
        offset = 1,
        pattern = "GTR",
      },
    },
    special_char = "!",
  },
  {
    description = "Global Tracker module",
    new_type = "m",
    signatures = {
      {
        offset = 152,
        pattern = {
          0x00,
          0xE1,
          0x00,
          0xD6,
          0x00,
          0xC8,
          0x00,
          0xBD,
          0x00,
          0xB2,
          0x00,
          0xA8,
          0x00,
          0x9F,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Pro Sound Creator v{ver} module wo/player",
    description_vars = { ver = { offset = 5, type = "ascii", length = 4 } },
    group = "trackers",
    comment = {
      length = 20,
      offset = 25,
    },
    author = {
      length = 20,
      offset = 49,
    },
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = "PSC V1.",
      },
    },
    special_char = "!",
    start = 21328,
    type = "M",
  },
  {
    description = "Pro Sound Creator 1.xx module",
    comment = {
      length = 45,
      offset = 3002,
    },
    new_type = "m",
    signatures = {
      {
        offset = 32,
        pattern = {
          0x22,
          nil,
          nil,
          0xEB,
          0x21,
          0x4C,
          0x00,
          0x19,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x22,
          nil,
          nil,
          0x2B,
          0x2B,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Pro Sound Maker v4.1 module",
    new_type = "m",
    signatures = {
      {
        offset = 301,
        pattern = {
          0xDD,
          0x35,
          0x0F,
          0xF0,
          0xDD,
          0x6E,
          0x00,
          0xDD,
          0x66,
          0x01,
          0xCD,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "SQ-Tracker Compiled module",
    group = "trackers",
    new_type = "m",
    special_char = "!",
    delta_check = true,
    header_check = {
      _offsets = {
        Size = 0,
        SamplesOffset = 2,
        OrnamentsOffset = 4,
        PatternsOffset = 6,
        PositionsOffset = 8,
        LoopPositionOffset = 10,
      },
      Size = { min = 256, max = 0x3600 },
      SamplesOffset = { min = 10, lt = "OrnamentsOffset" },
      OrnamentsOffset = { le = "PatternsOffset" },
      PatternsOffset = { lt = "PositionsOffset" },
      PositionsOffset = { le = "LoopPositionOffset" },
    },
  },
  {
    description = "SuperSonic module wo/player",
    new_type = "m",
    signatures = {
      {
        offset = 7,
        pattern = '(C) KLAV "S_SONIC"',
      },
    },
    special_char = "!",
  },
  {
    description = "SuperSonic module",
    new_type = "m",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xC3,
          nil,
          nil,
          0xC3,
          nil,
          nil,
          0xE6,
          0x03,
          0x87,
          0x5F,
          0x16,
          0x00,
          0x21,
        },
      },
    },
    special_char = "!",
  },
  {
    description = "Digital Music Maker module",
    new_type = "m",
    special_char = "!",
    start = 25000,
    type = "T",
  },
  {
    description = "Digital Studio tune",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "S",
  },
  {
    description = "Digital Studio module",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "M",
  },
  {
    description = "Digital Designer module",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "d",
  },
  {
    description = "Digital Designer module",
    new_type = "m",
    size = 0,
    special_char = "!",
    start = 0,
    type = "#",
  },
  {
    description = "Sample Tracker module",
    new_type = "m",
    special_char = "!",
    start = 35644,
    type = "s",
  },
  {
    description = "Sample Tracker module",
    new_type = "m",
    special_char = "!",
    start = 29280,
    type = "S",
  },
  {
    description = "Ultrasonic mod",
    new_type = "m",
    size = 25711,
    special_char = "!",
    start = 27987,
    type = "U",
  },
  {
    description = "Ultrasonic block",
    new_type = "m",
    size = 27503,
    special_char = "!",
    start = 27746,
    type = "1",
  },
  {
    description = "ZX-AMP Library",
    new_type = "m",
    special_char = "!",
    start = 21058,
    type = "L",
  },
  {
    description = "ZX-AMP Players pack",
    start = 20557,
    type = "A",
  },
  {
    description = "Packed with HRUST 2.1",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x68,
          0x72,
          0x32,
          0x31,
        },
      },
    },
  },
  {
    description = "Packed with HRUST 1.x",
    signatures = {
      {
        offset = 14,
        pattern = {
          0xD5,
          0xED,
          0xB0,
          0x13,
          0x13,
          0xD5,
          0xDD,
          0xE1,
          0x0E,
          0x06,
          0x09,
          0xED,
          0xB0,
        },
      },
    },
  },
  {
    description = "Packed with HRUST 1.x w/o depacker",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x48,
          0x52,
        },
      },
    },
  },
  {
    description = "Packed with HRUM 3.5i",
    signatures = {
      {
        offset = 5,
        pattern = {
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          0xED,
          0xB0,
          0x11,
          nil,
          nil,
          0xD9,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xC9,
        },
      },
    },
  },
  {
    description = "Packed with Rip",
    start = 28777,
    type = "R",
  },
  {
    description = "Packed with LZS",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xCD,
          nil,
          nil,
          0xF3,
          0xED,
          0x73,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xC9,
        },
      },
    },
  },
  {
    description = "Packed with Code Cruncher 3.1 (KSA)",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xF3,
          nil,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xC9,
        },
      },
    },
  },
  {
    description = "Packed with Compressor Code 4.1 (ZYX)",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xCD, -- CALL 0x0052 ; RET
          0x52,
          0x00,
          0x3B, -- DEC SP
          0x3B, -- DEC SP
          0xE1, -- POP HL
          0x01, -- LD BC, 0x0011
          0x11,
          0x00,
          0x09, -- ADD HL, BC
          0x11, -- LD DE, ADDR
          nil,
          nil,
          0x01, -- LD BC, LEN
          nil,
          nil,
          0xD5, -- PUSH DE
          0xED, -- LDIR
          0xB0,
          0xC9, -- RET
        },
      },
      {
        offset = 0,
        pattern = {
          0xF3,
          0xCD,
          0x52,
          0x00,
          0x3B,
          0x3B,
          0xE1,
          0x01,
          0x11,
          0x00,
          0x09,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          0xED,
          0xB0,
          0xC9,
        },
      },
    },
  },
  {
    description = "Packed with MS Pack",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xF3,
          0xED,
          0x73,
          nil,
          nil,
          0xD9,
          0x22,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          nil,
          0xD9,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          nil,
          nil,
          0xF9,
          0xE1,
        },
      },
    },
  },
  {
    description = "Packed with MS Pack w/o depacker",
    signatures = {
      {
        offset = 0,
        pattern = {
          "M",
          "s",
          "P",
          "k",
        },
      },
    },
  },
  {
    description = "Packed with PCD 6.xx",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xF3,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xC9,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
        },
      },
    },
  },
  {
    description = "Packed with PCD 6.xx (2)",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xF3,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xED,
          nil,
          0x01,
          nil,
          nil,
          0xD9,
          0x22,
          nil,
          nil,
          0x21,
        },
      },
    },
  },
  {
    description = "Packed with DSQ",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x11,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0xD5,
          0x01,
          nil,
          nil,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xC9,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0xD9,
          0xE5,
        },
      },
    },
  },
  {
    description = "Packed with Trush Packer",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xF3,
          nil,
          nil,
          0xD9,
          0xE5,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          nil,
          nil,
          0xEB,
          0x23,
          0xDD,
          0x21,
          nil,
          nil,
          0xDD,
          0x39,
          0xF9,
        },
      },
    },
  },
  {
    description = "Packed with ESV",
    signatures = {
      {
        offset = 0,
        pattern = {
          0xF3,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xD5,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          0xC9,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x01,
        },
      },
    },
  },
  {
    description = "Packed with Game Packer",
    signatures = {
      {
        offset = 0,
        pattern = {
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0xD5,
          0x01,
          nil,
          nil,
          nil,
          nil,
          0x21,
          nil,
          nil,
          0x11,
          nil,
          nil,
          0x01,
          nil,
          nil,
          nil,
          nil,
          0x13,
          0xEB,
          0x11,
          nil,
          nil,
          0xC9,
          0x7C,
          0xB5,
        },
      },
    },
  },
  {
    description = "AC Edit text",
    group = "ac_edit",
    new_type = "t",
    show_header = false,
    special_char = "!",
    type = "W",
    start = 0,
  },

  {
    description = "ZX Word text",
    new_type = "t",
    show_header = false,
    special_char = "!",
    type = "W",
  },
  {
    description = "BGE plugin",
    type = ">",
  },
}

return rules
